"""changed type ARRAY

Revision ID: 95cc7c394b8f
Revises: f4877d4e1c97
Create Date: 2025-08-26 18:31:26.439981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95cc7c394b8f'
down_revision: Union[str, Sequence[str], None] = 'f4877d4e1c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_prizes_id'), table_name='prizes')
    op.drop_table('prizes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prizes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('prizes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('prize_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel_link', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('winners_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('telegram_post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('isFinished', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('channels', postgresql.ARRAY(sa.INTEGER()), server_default=sa.text("'{}'::integer[]"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='prizes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_prizes_id'), 'prizes', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('prize_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['prize_id'], ['prizes.id'], name=op.f('users_prize_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('telegram_id', name=op.f('users_telegram_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###
